version: '3'
services:
    exercise-mysql:
        image: mysql:5.7
        ports:
          - "3306:3306"
        volumes:
          - mysql:/var/lib/mysql
        networks:
          - backend
    exerciseapi:
        build: .
        ports:
            - "5000:80"
        links:
            - exercise-mysql
        depends_on:
            - exercise-mysql
        networks:
            - backend
    exerciseweb:
      container_name: exerciseweb
      build: ./ExerciseWeb
      volumes:
        - '.:/app'
        - '/app/node_modules'
      ports:
        - "4200:4200"
      networks:
        - backend
        
### Networks Setup ############################################

networks:
    backend:
        driver: "bridge"
  
  ### Volumes Setup #############################################
  
volumes:
    mysql:
        driver: "local"
            